spring.application.name=EchoSync
server.port=8080

# H2 Configuration (Mock)
spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=

# Set debug logging for our app
logging.level.com.echosync=DEBUG
